baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
pluralizeListTitles = false

[Params]
    AuthorName = 'Tony'

# CopyRight string in the footer, change it to "" hide it
CopyRight = 'All Rights Reserved.'

# Social link in the footer, change it to "" hide it
[Social]
    github = " "
    facebook = " "
    twitter = " "
    email = " "

[markup]
    [markup.highlight]
        lineNoStart = 1
        lineNos = true
        style = "native"
        tabWidth = 4

[taxonomies]
    category = 'categories'
    author = 'author'
    tag = 'tags'
