baseURL = 'http://example.org/'
languageCode = 'en-us'

# What I preferred config
pluralizeListTitles = false

# Recommend syntax hilight config
[markup]
    [markup.highlight]
        lineNoStart = 1
        lineNos = true
        style = "native"
        tabWidth = 4

# Theme parameter
[params]

    # Customized info shown in header of the page
    [params.header]
        # Website title for header banner.
        title = "My New Hugo Site"

        # Config about your's site logo, remove this item to hide the logo
        [params.header.logo]
            # Where is your site's URL
            imgUrl = ""

            # If the logo is clickable, where should it be linked?
            # In default, it will linked to the homepage of the site.
            logoLink = ""

    # Customized info shown in footer of the page
    [params.footer]
        # CopyRight string shown in the footer. Keep it an empty string or remove this item will hide it from the page.
        copyrightStr = "All Rights Reserved ®."

        # Should show the counter in the footer or not
        # In the home page, it will show the numbers of all pages
        # In the sections pages, it will show the numbers of pages within the section
        # In the taxonomy pages, it will show the numbers of pages belong to the taxonomy.
        # In the regular content pages, it will show the word count.
        counter = true

        # Should show the language of the page or not
        language = true

        # Should show the hugo version or not
        hugoVersion = true

        # Should show the theme info or not
        theme = true

        # Should show the edited time of the page or not
        modifiedTime = true

        # Should show the current git HEAD hash or not
        # To make this show up correctly, please follow the prerequisites in page
        # https://gohugo.io/variables/git/
        gitHash = true

        # Social link in the footer, listed items are supported, delete unwanted items to hide it.
        [params.footer.socialLink]
            github = ""
            facebook = ""
            twitter = ""
            email = ""
            linkedin = ""
            instagram = ""
            telegram = ""
            medium = ""
            vimeo = ""
            youtube = ""


    # Metadata of the site, value will be used in HTML <header>
    # These value would be used when they didn't appear in the frontmatter of a single page.
    # In other words, these value will be overwritten by the frontmatter in the single page.
    [params.globalFrontmatter]
        # The author of this site. This will be shown in 
        # 1. the footer of all page
        # 2. the author filed in the single page. (this could be overwritten by the frontmatter of the single page.)
        # Keep it an empty string or remove this item will hide it from the page
        author = "Jing Wang"
        
        # Website description for RSS and SEO. Theme will generate a <meta> tag for this item
        description = "This is my new hugo site"

        # Website keywords. Theme will generate a <meta> tag for this item.
        keywords = "hugo,site,new"

        # Website ICON
        faviconUrl = ""

        # Do you need to add any external CSS? List them in an array.
        externalCss = []

        # Do you have any external Script need to add on? List them in an array.
        externalJs = []

    # Paramater applied in the single page
    # These values could be overwritten by the frontmatter in the single page.
    [params.page]
        # Should include Table of Content in front of the page or not.
        includeToc = true

        # Should show the author of the page or not.
        # The author name will be shown in the single page if and only if 
        #   1. this items been set as true and
        #   2. "aurthor" filed been provided in the 
        #       A. single page frontmatter or
        #       B. "author" filed in above "globalFrontmatter" block
        showAuthor = true

        # Should show the estimate reading time in front of the page or not.
        timeToRead = true

        # Should show the breadcrumb in front of the page or not.
        showBreadcrumb = true



