baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'

# What I preferred config
pluralizeListTitles = false

# Recommend syntax hilight config
[markup]
    [markup.highlight]
        lineNoStart = 1
        lineNos = true
        style = "native"
        tabWidth = 4

# Theme parameter
[Params]
    # CopyRight string in the footer, change it to "" hide it
    copyrightStr = 'All Rights Reserved.'
    
    # This name would be shown in the bottom of the page. It indicates the author of the site.
    authorName = 'Jing'

    # Should include Table of Content in front of the page or not.
    includeToc = true
    
    # Social link in the footer, delete unwanted items to hide it.
    [Social]
        github = " "
        facebook = " "
        twitter = " "
        email = " "