baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
assetDir = '/static'

# What I preferred config
pluralizeListTitles = false

# CopyRight string in the footer, change it to "" hide it
copyright = 'All Rights Reserved.'

# Site Authory Name
[Params]
    AuthorName = 'Jing'

# Social link in the footer, change it to "" hide it
[Social]
    github = " "
    facebook = " "
    twitter = " "
    email = " "

# Recommend syntax hilight config
[markup]
    [markup.highlight]
        lineNoStart = 1
        lineNos = true
        style = "native"
        tabWidth = 4

# Availabe tavnomies used with this theme
[taxonomies]
    category = 'categories'
    author = 'author'
    tag = 'tags'